services:
  web:
    container_name: otel-web
    build:
      context: ./packages/web
      dockerfile: Dockerfile
    ports:
      - '4173:4173'
    env_file:
      - ./packages/web/.env
    depends_on:
      alloy:
        condition: service_started
    networks:
      - app-network
    restart: unless-stopped

  api:
    container_name: otel-api
    build:
      context: ./packages/api
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    env_file:
      - ./packages/api/.env
    depends_on:
      alloy:
        condition: service_started
    networks:
      - app-network
    restart: unless-stopped

  alloy:
    container_name: otel-alloy
    build:
      context: ./packages/collector
      dockerfile: Dockerfile
    expose:
      - '4318' # OTLP HTTP for internal services
      - '4317' # OTLP gRPC for internal services
      - '12345' # OpenTelemetry configuration endpoint
    ports:
      - '12345:12345' # OpenTelemetry configuration endpoint
    env_file:
      - ./packages/collector/.env
    networks:
      - app-network
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    healthcheck:
      test: ['CMD', 'nc', '-z', 'localhost', '12345']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

volumes:
  alloy_data:
    driver: local

networks:
  app-network:
    name: otel-network
    driver: bridge
