version: '3.8'

services:
  alloy:
    container_name: alloy-testing
    build: .
    ports:
      - '12345:12345'
      - '4317:4317'
      - '4318:4318'
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
      - '/var/run/docker.sock:/var/run/docker.sock'
      - alloy_data:/var/lib/alloy/data
    env_file:
      - ./.env

volumes:
  alloy_data:
    driver: local
